# Site settings
title: King's blog
email: 
description: "Place where I write down my thoughts."
baseurl: ""
url: "http://nguynking.github.io"
twitter_username: nguynking
github_username:  nguynking

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
